version: '3.8'

services:
  db:
    image: postgres:17
    container_name: hotel_booking_db
    environment:
      POSTGRES_DB: hotel_booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ./hotel-booking-backend
      dockerfile: Dockerfile
    container_name: hotel_booking_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hotel_booking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root@123
    depends_on:
      - db

volumes:
  postgres_data: